gqlalchemy/__init__.py
gqlalchemy/models.py
tests/conftest.py
tests/data/nodes_and_edges.cyp
tests/data/path.cyp
tests/intergration/test_constraints.py
tests/intergration/test_index.py
tests/intergration/test_memgraph.py
tests/memgraph/test_utilities.py

Add tests for:
- `utilities.py`
- memgraph mapping for Node, Relationship and Path

Add missing tests

---

gqlalchemy/transformations.py
tests/test_transformations.py

This PR fixes an issue when nx graph has ids which are strings.

Fix networkx transformation when ids are string

---

README.md
gqlalchemy/__init__.py
gqlalchemy/connection.py
gqlalchemy/exceptions.py
gqlalchemy/memgraph.py
gqlalchemy/models.py
gqlalchemy/utilities.py
tests/intergration/test_memgraph.py
tests/intergration/test_networkx.py
tests/ogm/automatic_deserialisation_test.py
tests/ogm/multiple_inheritance_test.py
tests/ogm/serialisation_test.py

This PR aims to create a way for Python objects to be saved into Memgraph using Merge and Create. The operations have to support only internal `Field` objects and respect the arguments given to them (`index`, `exists`, `unique`, primary_key`, `on_disk`)...
related:
#60 
Here is a list of all supported data types.
The node gets **created** in Memgraph, `MATCH` and `MERGE` are not used in the cypher, only `CREATE` is used.
```python
class MyNode(Node):
name: Optional[str] = Field()
done: Optional[bool]
unit: Optional[int] = Field()
time: Optional[float]
keys: Optional[list[int]]
tags: Optional[dict[str, float]]
date: Optional[datetime.datetime] = Field()
node = MyNode(name="First")
node.save(db)
```
When the node is first inserted into Memgraph, the Memgraph internal id is set on the node …

OGM: saving python objects to Memgraph

---

.gitignore
gqlalchemy/__init__.py
gqlalchemy/disk_storage.py
gqlalchemy/exceptions.py
gqlalchemy/memgraph.py
gqlalchemy/models.py
tests/on_disk_property_storage/test_multiprocess.py
tests/on_disk_property_storage/test_query.py

add property database interface

---

README.md
docs/reference/gqlalchemy/connection.md
docs/reference/gqlalchemy/disk_storage.md
docs/reference/gqlalchemy/memgraph.md
docs/reference/gqlalchemy/models.md
docs/reference/gqlalchemy/query_builder.md
docs/reference/gqlalchemy/transformations.md
docs/reference/gqlalchemy/utilities.md
docs/reference/sidebar.json
gqlalchemy/connection.py
gqlalchemy/disk_storage.py
gqlalchemy/exceptions.py
gqlalchemy/memgraph.py
gqlalchemy/models.py
gqlalchemy/query_builder.py
gqlalchemy/transformations.py
gqlalchemy/utilities.py
pydoc-markdown.yml

Adding code documentation that is missing.

add code documentation

---

poetry.lock
pyproject.toml

Merging changes from `main` into `develop` to update the version of pymgclient to 1.2.0 and GQLAlchemy to 1.1.3.

Update pymgclient version

---

gqlalchemy/memgraph.py

Fixed save node signature in a method

---

gqlalchemy/memgraph.py
tests/ogm/test_serialisation.py

Add methods for batch saving nodes and relationships to the database:
Closes #64

[develop < T0021-GA] Add batch save methods

---

gqlalchemy/exceptions.py
gqlalchemy/models.py
tests/integration/test_index.py

With this new feature, it's possible to create an index on the label. Up until now, it was only possible to create an index on certain node properties. 
Documentation: How-to guide on Docs https://github.com/memgraph/docs/pull/339
Closes https://github.com/memgraph/gqlalchemy/issues/102

[develop < T0040-GA] Add index on label

---

tests/memgraph/test_query_builder.py

[develop < T0027-GA] Add tests for using nodes and relationships in the query builder

---

gqlalchemy/models.py
tests/ogm/test_class_definition.py

[develop < T0020-GA] Fix label inheritance

---

README.md

I've updated README with working examples and all GQLAlchemy capabilities. If it's too much info, I can revert to old README with the correct working examples.

[master <  T0068-GA] Update README

---

gqlalchemy/memgraph.py
gqlalchemy/query_builder.py

[develop < T0071-GA-bfs-and-shortest-path] added base class and integrated into edge query

---

gqlalchemy/exceptions.py
gqlalchemy/query_builder.py
tests/memgraph/test_query_builder.py

Added SET method to query builder.
Closes #126 

[develop < T0059-GA] Add SET method to the query builder

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
gqlalchemy/memgraph.py

host and port read only

---

gqlalchemy/query_builder.py
gqlalchemy/utilities.py
tests/memgraph/test_query_builder.py

What the title says.
Closes #137 

[develop < T0094-GA] Variable support for node and edge properties

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
gqlalchemy/memgraph.py

new connection private method

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
gqlalchemy/connection.py
gqlalchemy/exceptions.py
tests/integration/test_stream.py

exceptions fixed

---

gqlalchemy/memgraph.py
tests/memgraph/test_memgraph.py

Add argument `lazy` for configuring lazy loading in the `Memgraph` class.

Add argument `lazy` to `Memgraph`

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
gqlalchemy/memgraph.py

Fixes the unbound variable error in the return statement of the cypher query in `memgraph.save_relationship_with_id()`.
Bugfix

fix bad query in save_relationship_with_id

---

gqlalchemy/query_builder.py
gqlalchemy/utilities.py
poetry.lock
tests/docs/test_query_builder.py

[develop < T0093] Add query module arguments as tuples

---

.github/CODEOWNERS
poetry.lock
pyproject.toml

Update pymgclient and change CODEOWNERS file.

[master < T0112-GA] Update pymgclient

---

README.md

I added information on installing GQLAlchemy in Conda env.

[master < T0113-GA] Add Conda info to README

---

.github/workflows/build-and-test.yml
gqlalchemy/exceptions.py
poetry.lock
pyproject.toml

Fixed exception handling in GQLAlchemyWaitForConnectionError and GQLAlchemyDatabaseError (added `raise from`). This PR extended PR https://github.com/memgraph/gqlalchemy/pull/187 and it closes it.

[main < T0116-GA] Fix GQLAlchemyWaitForConnectionError and GQLAlchemyDatabaseError

---

poetry.lock
pyproject.toml

[main < T0121-GA] Update poetry packages

---

README.md

In the README file for this project code for Pulsar is placed under the Kafka section and vice versa.
Closes [(196)](https://github.com/memgraph/gqlalchemy/issues/196)

[master < fix-readme-examples] Fix the order of code samples

---

.github/workflows/build-and-test.yml

Bump Poetry version to fix Windows + python 3.9 build pipeline

Bump poetry version to 1.2.2

---

gqlalchemy/graph_algorithms/integrated_algorithms.py
pyproject.toml
tests/query_builders/test_memgraph_query_builder.py

Added support for the new all shortest paths algorithm to integrated_algorithms.py

[develop < T0122] add AllShortest support

---

pyproject.toml

I updated the versioning in `pyproject.toml` (this should be done with 1.3.3 release). PR is on `main` since this is a fix that should be pushed directly to `main` (aligned with 1.3.3) - after we should propagate it to `develop`.

[main < update-pyproject] Update versioning in pyproject.toml

---

gqlalchemy/query_builders/declarative_base.py
pyproject.toml

I updated the docstring related to #218.

[develop < update-docstring-and-pyproject] Update docstring

---

gqlalchemy/connection.py
gqlalchemy/vendors/database_client.py
tests/test_query.py

The `mgclient` has support for accepting parameters with a query to execute. I added functionality so the Connection and DatabaseClient classes can accept these as well. 
Honestly, I did this in 15 minutes to get something working for myself and wanted to share it. I felt this was better than submitting an issue since I had already done some work on it. I don't think this is terribly complicated but, to me, it's a core feature and so I think it would be better implemented by a regular maintainer who knows where the tests live, the style guidelines, etc.

Add parameters to execute methods

---

pyproject.toml

Bump version to 1.4 for release

---

.github/CODEOWNERS
docs/reference/gqlalchemy/connection.md
docs/reference/gqlalchemy/disk_storage.md
docs/reference/gqlalchemy/exceptions.md
docs/reference/gqlalchemy/graph_algorithms/integrated_algorithms.md
docs/reference/gqlalchemy/graph_algorithms/query_modules.md
docs/reference/gqlalchemy/instance_runner.md
docs/reference/gqlalchemy/models.md
docs/reference/gqlalchemy/query_builders/declarative_base.md
docs/reference/gqlalchemy/query_builders/memgraph_query_builder.md
docs/reference/gqlalchemy/transformations/export/graph_transporter.md
docs/reference/gqlalchemy/transformations/export/transporter.md
docs/reference/gqlalchemy/transformations/importing/graph_importer.md
docs/reference/gqlalchemy/transformations/importing/loaders.md
docs/reference/gqlalchemy/transformations/translators/dgl_translator.md
docs/reference/gqlalchemy/transformations/translators/nx_translator.md
docs/reference/gqlalchemy/transformations/translators/pyg_translator.md
docs/reference/gqlalchemy/transformations/translators/translator.md
docs/reference/gqlalchemy/utilities.md
docs/reference/gqlalchemy/vendors/database_client.md
docs/reference/gqlalchemy/vendors/memgraph.md
docs/reference/gqlalchemy/vendors/neo4j.md
docs/reference/sidebar.json
pydoc-markdown.yml

I regenerated the reference guide and we should do this with every release and accordingly update reference guide on the Docs repo.

Update reference guide

---

docs/how-to-guides/ogm.md
docs/how-to-guides/query-builder.md
docs/how-to-guides/translators/export-python-graphs.md
docs/how-to-guides/translators/import-python-graphs.md
docs/how-to-guides/triggers/triggers.md
docs/import-data.md

I've updated the lists in the documentation so that they render as they should.
Closes https://github.com/memgraph/gqlalchemy/issues/268

[main < 286-markdown-lists...] Update Markdown code for the lists

---

gqlalchemy/vendors/memgraph.py

Fix typing for `get_triggers` method.
- [ X] Code style update (formatting, renaming)
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes

Fix typing

---

README.md
docs/how-to-guides/instance-runner/memgraph-binary-instance.md
docs/how-to-guides/instance-runner/memgraph-docker-instance.md
docs/how-to-guides/loaders/import-table-data-to-graph-database.md
docs/how-to-guides/loaders/make-a-custom-file-system-importer.md
docs/how-to-guides/overview.md
docs/installation.md
docs/reference/gqlalchemy/graph_algorithms/query_modules.md
docs/reference/gqlalchemy/models.md
docs/reference/gqlalchemy/transformations/translators/dgl_translator.md
docs/reference/gqlalchemy/vendors/memgraph.md

This PR adds the documentation for #279 and makes miscellaneous small corrections.
Changelog (for #279 and this PR):
> To make GQLAlchemy more secure, Docker will be an optional dependency until the vulnerabilities in the `pywin32` library (required by Docker) are patched.

[main < T280] Document that Docker is an optional dependency

---

README.md
docs/changelog.md
docs/installation.md
pyproject.toml

README, docs and version update.

Update readme, docs, and version

---

docs/how-to-guides/instance-runner/memgraph-docker-instance.md
docs/index.md
docs/installation.md

I've updated two admonitions related to Python version and fixed one broken link.

[main < docs-formating-fix-20230922] Update admonitions and link

---

docs/index.md

Added code snippet on how to connect to Memgraph.
Closes #296

Update connect to Memgraph

---

README.md
docs/changelog.md
docs/installation.md
pyproject.toml

Update version to 1.7.0

---

.github/workflows/publish-docs.yml

Added missing dependency for publish docs workflow

Added missing dependency for publish docs workflow
