memgraph/gqlalchemy

- .github/workflows/build-and-test.yml
- gqlalchemy/transformations.py
- poetry.lock
- pyproject.toml
- pytest.ini
- tests/conftest.py
- tests/intergration/__init__.py
- tests/intergration/test_networkx.py
- tests/test_transformations.py
Integrate networkx graph to cypher queries transformation.
Currently there are two new API calls to `gqlalchemy.tranformations`:
- `nx_to_cypher`
- `nx_graph_to_memgraph_parallel`
Accepts a networkx graph and translates it into two (or three) groups of cypher queries. The first group is a creation of nodes, second is optional (if the caller passes `create_index` as `True`) you will get queries for creating indexes on `id` property, and this is a creation of edges.
Accepts a networkx graph and connection parameters for creating multiple connections to memgraph which will be used to insert the whole networkx graph in memgraph in parallel. It also supports `create_index` flag, if set the function will create all indexes an `id` property.
Using this module assumes some stuff:
- If you create …
> Add networkx transformation

- gqlalchemy/transformations.py
- gqlalchemy/utilities.py
- tests/intergration/test_networkx.py
- tests/memgraph/test_utilities.py
- tests/test_transformations.py
Added additional configuration to handle NaN values when converting from nxGraph to Cypher queries. The default configuration raises NanException. Additional handle for Nan values is provided - yielding null if nan occurs, therefore the property will not be added when injecting queries to Memgraph.
> Add support for handling NaN values when converting nx to cypher

- README.md
- gqlalchemy/query_builder.py
- pyproject.toml
This PR adds support for querying Memgraph using Node and Relationship objects:
Here's an example
```python
from gqlalchemy import Memgraph, Node, Relationship, Match
memgraph = Memgraph("127.0.0.1", 7687)
memgraph.execute("CREATE (:Node {id: 1})-[:RELATED_TO {id: 1}]->(:Node {id: 2})")
a = Node(1, ["Node"], {'id': 1})
b = Node(2, ["Node"], {'id': 2})
r = Relationship(1, "RELATED_TO", 1, 2, {'id': 1})
result = list(
Match(memgraph.new_connection())
.node(variable="a", node=a)
.to(variable="r", relationship=r)
.node(variable="b", node=b)
.execute()
)[0]
print(result['a'])
print(result['b'])
print(result['r'])
```
> add match support for objects

- README.md
Currently it's only static, but better than nothing. It links to the actual milestone.
> add v1.1 release progress bar

- gqlalchemy/query_builder.py
- tests/memgraph/test_query_builder.py
The `add_custom_cypher()` method enables the user to add any string to the query builder. It is needed because there are functionalities that still need to be implemented inside the query builder.
> Add custom string method to query builder

- gqlalchemy/memgraph.py
- tests/intergration/test_stream.py
A method was missing for the Cypher construct `START STREAM <stream name>;`.
> Add start_stream() method

- gqlalchemy/memgraph.py
- gqlalchemy/models.py
- tests/integration/test_trigger.py
> [develop < T0013-GA] Create trigger without ON

- gqlalchemy/query_builder.py
- pyproject.toml
Remove the argument optional from the Merge class
This PR closes issue #117 
> [main < T0049-GA] Remove the argument optional from the Merge class

- gqlalchemy/exceptions.py
- gqlalchemy/query_builder.py
- tests/docs/test_ogm.py
- tests/docs/test_query_builder.py
- tests/memgraph/test_query_builder.py
Changed `where()`, `and_where()`, `or_where()` and `xor_where()` methods (added keyword arguments). Now label can be used as a left-hand side value in where clause.
Added tests for all methods.
Closes https://github.com/memgraph/gqlalchemy/issues/74
> [develop < T0039-GA] Change where procedure in query builder

- gqlalchemy/exceptions.py
- gqlalchemy/query_builder.py
- tests/memgraph/test_query_builder.py
What's new:
- Exceptions for ordering.
- Enums for Where (WHERE, AND, OR, XOR, NOT) and Order (ASC, ASCENDING, DESC, DESCENDING).
- All where methods (where, and, or, xor) use their classes to construct queries. Those classes inherit from the `WhereConditionPartialQuery` class. 
- All where_not methods (where_not, and_not, or_not, xor_not) use their classes to construct queries. Those classes inherit from the `WhereNotConditionPartialQuery` class, which inherits from the `WhereConditionPartialQuery` class.
- There is one order_by method that allows either property (default ascending order), a tuple of property and order, or a list of either property or tuple of property and order.
> [develop < T0046-GA] Add order by descending

- .github/pull_request_template.md
I updated our PR template with sentence to delete unchecked PR types and added the 'closes' keyword to linked issues that should automatically close the related issue. I also added a checklist that made sense to me but feel free to suggest changes.
> [develop < T0043-GA] Update PR template

- gqlalchemy/__init__.py
- gqlalchemy/query_builder.py
- tests/memgraph/test_query_builder.py
Added load_csv and return to base classes list.
Discuss:
REMOVE, DELETE and SET  are also supported per cypher grammar to be at the start of a query, but I have not included them as in agreement with Ivan they do not make much sense to be used like that, without some variable defined with MATCH in front of them.
Note:
FOREACH will also be in the base classes, but I decided to add it to the FOREACH clause PR, so this PR doesn't have to wait for that one.
Closes #138 
> [develop < T0070-GA] Add more clauses for base classes

- gqlalchemy/exceptions.py
- gqlalchemy/loaders.py
- gqlalchemy/memgraph.py
- gqlalchemy/query_builder.py
- tests/docs/test_ogm.py
- tests/docs/test_query_builder.py
- tests/memgraph/test_query_builder.py
I created `Operator` `Enum`. This Enum holds operators for `SET` and `WHERE` clauses. I added all operators that are a part of [`partialComparisonExpression` in the Cypher grammar](https://github.com/memgraph/memgraph/blob/69eca9b0437a3370d13a01669b8eabbcc9ff9599/src/query/frontend/opencypher/grammar/Cypher.g4#L259).  I updated all tests accordingly and left a couple of examples showing that the previous solution with a simple string operator works (backward compatibility).
Not sure if the operators should be used across the documentation (how-to guides and docstrings) or a simple string - it is a question for both `WHERE` and `SET` clauses. @g-despot ?
> [develop <  T0089-GA] Create Operator Enum

- gqlalchemy/query_builder.py
After @BorisTasevski noted checking for `None` in a property that is not of type `Optional[...]` is not consistent, I looked at other `@property` uses. 
- for `NodePartialQuery` and `RelationshipPartialQuery` value argument, which is optional, I turned the double negative if-else expression into positive logic, as we previously discussed was easier to understand.
- for arguments `labels` and `properties`, along with `RemovePartialQuery` and `DeletePartialQuery` arguments, I removed the checking and Optional support since they go through their respective `to_cypher_` methods first, which assigns them an empty string if they are `None` to begin with. This is something to discuss, if you think we should still support this for flexibility (e.g. if we were to change `to_cypher_properties` …
> [develop < T0106] fix @property being optional when they are not

- README.md
- gqlalchemy/query_builders/declarative_base.py
I changed Iterable to correct argument type. It was accidentally left unchanged from the previous [PR](https://github.com/memgraph/gqlalchemy/pull/146).
> [develop < T0109-GA] Remove excess Iterable type

- README.md
Someone probably changed the link for table importer how-to guides, which now doesn't include `/loaders/`. Some of the how-to guides contain the category, and some don't.
- x ] New and existing unit tests pass locally with my changes
> Fix links for table data importer

- .github/workflows/build-and-test.yml
- gqlalchemy/graph_algorithms/query_builder.py
- Make build-and-test.yml MG_VERSION 2.5.0
- Make Ubuntu version used 20.04 (as it is already in develop), because for some reason 22.04 has that issue that libpython is not installed and needed for memgraph. This is definitely a problem in the future when we want to use the newer Ubuntu.
> [main < ] change Ubuntu and MG version in workflow

- gqlalchemy/query_builders/memgraph_query_builder.py
- gqlalchemy/utilities.py
- tests/query_builders/test_memgraph_query_builder.py
- tests/query_builders/test_neo4j_query_builder.py
- tests/query_builders/test_query_builders.py
Added support for graph project feature while trying to make it easy to use. The idea is to pass a node label and relationship types that you want to use in the subgraph to the `call` method for query modules. GQLAlchemy constructs the query for project and inserts the `graph` argument in the query module call. both can be as many as you like. Given that the labels and types are used to construct the match part of the query, I also included the possibility to use `subgraph_query` argument and insert the Cypher path in string form.
Notes:
- I added the ProjectPartialQuery, which is a MATCH - WITH query, I used `DeclarativeBaseTypes.MATCH` as its type. This and the construction of the MATCH query could have been done in other ways, for instance using QueryBuilder methods, but I did it like …
> [develop < T0123] Graph project implementation

- .github/workflows/build-and-test.yml
- gqlalchemy/exceptions.py
- gqlalchemy/transformations/export/graph_transporter.py
- gqlalchemy/transformations/importing/graph_importer.py
- gqlalchemy/transformations/importing/loaders.py
- gqlalchemy/transformations/translators/dgl_translator.py
- gqlalchemy/transformations/translators/pyg_translator.py
- gqlalchemy/transformations/translators/translator.py
- gqlalchemy/utilities.py
- poetry.lock
- pyproject.toml
- pytest.ini
- tests/transformations/export/test_export.py
- tests/transformations/importing/test_import.py
- tests/transformations/loaders/test_loaders.py
- tests/transformations/translators/test_dgl_transformations.py
- tests/transformations/translators/test_nx_transformations.py
- tests/transformations/translators/test_pyg_transformations.py
In order to make installing GQLAlchemy easier, this PR makes large dependencies (pyarrow, dgl and torch) optional:
`pip install gqlalchemy` ← skips the dependencies
`pip install gqlalchemy[arrow]` ← installs pyarrow:
dgl and torch are grouped because dgl-specific features also use torch for data structures:
* `pip install gqlalchemy[dgl]`← installs dgl and torch
Alternatively, users who wish to install PyG manually can install just torch:
* `pip install gqlalchemy[torch_pyg]`← installs torch
The `all` extra covers all above dependencies:
`pip install gqlalchemy[all]` ← installs everything
Closes #178 #226 #227 #230 
> Make large dependencies optional

- .github/workflows/build-and-test.yml
- gqlalchemy/graph_algorithms/query_builder.py
- tests/graph_algorithms/test_query_builder.py
- tests/integration/test_constraints.py
Updated procedures signatures to match the latest Memgraph. Skipped test for procedure signatures. Updated test for constraint to remove reserved keyword text in the latest Memgraph.
> Add latest signatures

- docs/how-to-guides/loaders/import-table-data-to-graph-database.md
- docs/reference/gqlalchemy/transformations/importing/loaders.md
- gqlalchemy/transformations/importing/loaders.py
- tests/transformations/loaders/data/address.csv
- tests/transformations/loaders/data/i2a.csv
- tests/transformations/loaders/data/individual.csv
- tests/transformations/loaders/test_loaders.py
Define relationship properties in many_to_many via name_mappings and properties field
> Adds properties on edges

- gqlalchemy/query_builders/declarative_base.py
- tests/query_builders/test_query_builders.py
Add regex operator (it already exists in Memgraph).
closes #267 
> Add regex operator

- .github/workflows/build-and-test.yml
- gqlalchemy/vendors/memgraph.py
- tests/ogm/test_transactions.py
I added get transactions and terminate transactions methods for easier transaction management.
Closes #240 
> Add transactions queries

- .github/workflows/build-and-test.yml
- gqlalchemy/vendors/memgraph.py
- tests/conftest.py
- tests/integration/test_storage_modes.py
- tests/ogm/test_storage_modes.py
I added getter and setter for storage modes. I also updated the test setup to set storage mode to in-memory transactional by default. 
Closes #239 
> Add storage mode info

- docs/changelog.md
- pyproject.toml
> Update changelog and version
